// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoNp_hN_4NAiCvXlM3beSH-_NRLMJ33n4',
    appId: '1:1078810035647:web:73f401251727fd17adcd0a',
    messagingSenderId: '1078810035647',
    projectId: 'herlytics',
    authDomain: 'herlytics.firebaseapp.com',
    storageBucket: 'herlytics.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW_X6rrtJV1plP95bYbP4NN6yU3IOFCnE',
    appId: '1:1078810035647:android:7cc0625a14515e45adcd0a',
    messagingSenderId: '1078810035647',
    projectId: 'herlytics',
    storageBucket: 'herlytics.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo70qT0-70CvAjeMnAW7m427v6lF9NYSQ',
    appId: '1:1078810035647:ios:305b7c3e576b2a25adcd0a',
    messagingSenderId: '1078810035647',
    projectId: 'herlytics',
    storageBucket: 'herlytics.appspot.com',
    iosBundleId: 'com.example.herlytics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCo70qT0-70CvAjeMnAW7m427v6lF9NYSQ',
    appId: '1:1078810035647:ios:305b7c3e576b2a25adcd0a',
    messagingSenderId: '1078810035647',
    projectId: 'herlytics',
    storageBucket: 'herlytics.appspot.com',
    iosBundleId: 'com.example.herlytics',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoNp_hN_4NAiCvXlM3beSH-_NRLMJ33n4',
    appId: '1:1078810035647:web:39d879bd0cec9574adcd0a',
    messagingSenderId: '1078810035647',
    projectId: 'herlytics',
    authDomain: 'herlytics.firebaseapp.com',
    storageBucket: 'herlytics.appspot.com',
  );
}
